name: Build Native
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: graalvm/setup-graalvm@v1
        with:
          version: 'latest'
          java-version: '17'
          components: 'native-image'
      - name: Make staging directory
        run: mkdir staging
      - name: Build JAR with Maven
        run: mvn -B package
      - name: Copy JAR to staging
        run: cp target/*.jar staging
      - name: Gluon Build
        run: mvn gluonfx:build
      - name: Copy native client to staging
        run: cp -r target/gluonfx/x86_64-linux/SprintCapaCalc* staging
      - name: Upload
        uses: actions/upload-artifact@v3
        with:
          name: Package
          path: staging
