name: MacOS

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macOS-latest
    steps:
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '11.7.0'
      - uses: actions/checkout@v2
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '21.0.0.java11'
      - name: Install native-image component
        run: gu install native-image
      - name: Make staging directory
        run: mkdir staging
      - name: Build JAR with Maven
        run: mvn -B package
      - name: Copy JAR to staging
        run: cp target/*.jar staging
      - name: Gluon Build
        run: mvn client:build
      - name: Copy native client to staging
        run: cp -r target/client/x86_64-darwin/SprintCapaCalc* staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
