name: Windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - name: Add msbuild to PATH
        uses: microsoft/setup-msbuild@v1.0.2
      - name: Visual Studio shell
        uses: egor-tensin/vs-shell@v1
      - name: Setup Graalvm
        id: setup-graalvm
        uses: DeLaGuardo/setup-graalvm@master
        with:
          graalvm-version: '22.0.0.2.java17'
      - name: Install native-image component
        run: gu.cmd install native-image
      - name: Make staging directory
        run: mkdir staging
      - name: Build JAR with Maven
        run: mvn -B package
      - name: Copy JAR to staging
        run: cp target/*.jar staging
      - name: Gluon Build
        run: mvn gluonfx:build
      - name: Copy native client to staging
        run: cp -r target/gluonfx/x86_64-windows/*.exe staging
      - name: Upload
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: staging
